### ISSUE TITLE
 CUDA error: CUBLAS_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by rabeehk** [THUDM/FewNLU#1]
Hi
Thanks for the codes.
I am trying with this command:
```
python3 cli.py           --method pet           --arch_method default           --data_dir /data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/data/fewglue/FewGLUE/BoolQ          --pattern_ids 0           --model_type albert           --model_name_or_path albert-xxlarge-v2           --dataset_name superglue           --task_name boolq          --output_dir /fsx/rkarimi/test/test1           --do_eval           --do_train           --per_gpu_eval_batch_size 4           --per_gpu_train_batch_size 4           --gradient_accumulation_steps 1           --max_seq_length 128           --max_steps 10           --sampler_seed 1           --seed 1           --warmup_step_ratio 0           --learning_rate 1e-5           --repetitions 1           --use_cloze           --few_shot_setting dev32_split           --every_eval_ratio 0.02           --cv_k 4           --split_ratio 0.5           --fix_deberta --overwrite_output_dir 
```
getting this error:

```
Traceback (most recent call last):
  File "cli.py", line 584, in <module>
    main()
  File "cli.py", line 518, in main
    results=iterative_run(dataprovider, eval_data, wrapper_config, train_eval_config, unlabeled_data, aug_data, output_dir=args.output_dir)
  File "cli.py", line 248, in iterative_run
    results=run(dataprovider, eval_data, wrapper_config, train_eval_config, output_dir, unlabeled_data, aug_data, save_unlabeled_logits=False)
  File "cli.py", line 349, in run
    unlabeled_data=unlabeled_data, ipet_train_data=ipet_train_data)
  File "/data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/fewnlu/wrapper.py", line 215, in train
    ** train_eval_config.__dict__)
  File "/data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/fewnlu/wrapper.py", line 350, in _train
    priming_num, priming_data=train_data,use_dropout=False)["scores"] if dev32_data is not None else None
  File "/data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/fewnlu/wrapper.py", line 235, in evaluate
    use_dropout=use_dropout)
  File "/data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/fewnlu/wrapper.py", line 529, in _eval
    logits = self.model.eval_step(batch,**eval_step_inputs)
  File "/data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/fewnlu/methods/pet/pet_model.py", line 30, in eval_step
    outputs = self(**inputs)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/home/rkarimi/codes/fewshot/internship/fewshot/temp/FewNLU/fewnlu/methods/base_model.py", line 58, in forward
    labels=labels, **kwargs)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/transformers/models/albert/modeling_albert.py", line 939, in forward
    return_dict=return_dict,
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/transformers/models/albert/modeling_albert.py", line 714, in forward
    return_dict=return_dict,
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/transformers/models/albert/modeling_albert.py", line 448, in forward
    hidden_states = self.embedding_hidden_mapping_in(hidden_states)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/fsx/rkarimi/conda/envs/fewnlu/lib/python3.7/site-packages/torch/nn/functional.py", line 1612, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Could you kindly confirm the version of CUDA/torch working with your codes.  thanks

**Comment by rabeehk** [comment]
solvd with installing pytorch 1.7 instead of 1.5 mentioned in the requirements. thanks
